{
	"version": 1617032252,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/alien1-sheet0.png",
		"images/alien1shadow-sheet0.png",
		"images/alien2-sheet0.png",
		"images/alien2-sheet1.png",
		"images/alien2_shadow-sheet0.png",
		"images/alien3-sheet0.png",
		"images/alien3-sheet1.png",
		"images/alien4-sheet0.png",
		"images/alien4-sheet1.png",
		"images/alien5-sheet0.png",
		"images/alien5-sheet1.png",
		"images/alien6-sheet0.png",
		"images/alien6-sheet1.png",
		"images/animacjatrafieniapociskiemramdo_-sheet0.png",
		"images/animacjawystrzalualiena_-sheet0.png",
		"images/bg-sheet0.png",
		"images/checkpt-sheet0.png",
		"images/kularamdo-sheet0.png",
		"images/kularamdo-sheet1.png",
		"images/kularamdo-sheet2.png",
		"images/shotaliena_-sheet0.png",
		"images/shotaliena_-sheet1.png",
		"images/shotaliena_2-sheet0.png",
		"images/shotaliena_2-sheet1.png",
		"images/playeranim-sheet0.png",
		"images/playeranim-sheet1.png",
		"images/playerlegs-sheet0.png",
		"images/playerlegs-sheet1.png",
		"images/alien5_shadow-sheet0.png",
		"images/alien6_shadow-sheet0.png",
		"images/alien7-sheet0.png",
		"images/alien7-sheet1.png",
		"images/alien8-sheet0.png",
		"images/alien8-sheet1.png",
		"images/alien8-sheet2.png",
		"images/lasergora_-sheet0.png",
		"images/lasergora_-sheet1.png",
		"images/lasergora_-sheet2.png",
		"images/lasersegment_-sheet0.png",
		"images/lasersegment_-sheet1.png",
		"images/granadeexplosion_-sheet0.png",
		"images/granadeexplosion_-sheet1.png",
		"images/lecacygranatrambo_-sheet0.png",
		"images/lecacygranatrambo_-sheet1.png",
		"images/lecacygranatrambo_-sheet2.png",
		"images/wybuchgranatuobcych_-sheet0.png",
		"images/bonusmedal-sheet0.png",
		"images/bonusmedal-sheet1.png",
		"images/bonusmedal-sheet2.png",
		"images/licznikzyciabossa-sheet0.png",
		"images/licznikzyciabossa-sheet1.png",
		"images/licznikzyciabossa-sheet2.png",
		"images/skrzynkazbajerami_-sheet0.png",
		"images/skrzynkazbajerami_-sheet1.png",
		"images/tirerobal-sheet0.png",
		"images/tirerobal-sheet1.png",
		"images/brickmonster-sheet0.png",
		"images/violetmonster-sheet0.png",
		"images/violetmonster-sheet1.png",
		"images/vomitek-sheet0.png",
		"images/vomitek-sheet1.png",
		"images/vomitek-sheet2.png",
		"images/hugerobal-sheet0.png",
		"images/hugerobal-sheet1.png",
		"images/hugerobal-sheet2.png",
		"images/btnbacktomain-sheet0.png",
		"images/btnbacktomain-sheet1.png",
		"images/btnsoundunmute-sheet0.png",
		"images/btnsoundunmute-sheet1.png",
		"images/btnsoundmute-sheet0.png",
		"images/btnsoundmute-sheet1.png",
		"images/btnplay-sheet0.png",
		"images/btnplay-sheet1.png",
		"images/btncontinue-sheet0.png",
		"images/btncontinue-sheet1.png",
		"images/btnpause-sheet0.png",
		"images/btnpause-sheet1.png",
		"images/btnrestart-sheet0.png",
		"images/btnrestart-sheet1.png",
		"images/btnclaim-sheet0.png",
		"images/btnclaim-sheet1.png",
		"images/btnskip-sheet0.png",
		"images/btnskip-sheet1.png",
		"images/btnrevive-sheet0.png",
		"images/btnswitchgame-sheet0.png",
		"images/pausecurtain.png",
		"images/gameplaybackground-sheet0.png",
		"images/gametitle2-sheet0.png",
		"images/flashscreen-sheet0.png",
		"images/highscorelabel-sheet0.png",
		"images/coverillustration-sheet0.png",
		"images/pausedcurtain-sheet0.png",
		"images/scorepanel-sheet0.png",
		"images/ikona_serce-sheet0.png",
		"images/ikona_serce-sheet1.png",
		"images/avatarimg-sheet0.png",
		"images/blackscreen-sheet0.png",
		"images/bossfight-sheet0.png",
		"images/gamecompleted_bg-sheet0.png",
		"images/hitlay-sheet0.png",
		"images/htp_touch_-sheet0.png",
		"images/kolowywykresprogressu_-sheet0.png",
		"images/kolowywykresprogressu_-sheet1.png",
		"images/linelb-sheet0.png",
		"images/powerupiconui-sheet0.png",
		"images/powerupiconui-sheet1.png",
		"images/poweruptimeleft-sheet0.png",
		"images/locked-sheet0.png",
		"images/questdailylabel-sheet0.png",
		"images/dialog_alien-sheet0.png",
		"images/dialog_alien-sheet1.png",
		"images/characterlevel-sheet0.png",
		"images/panel-sheet0.png",
		"images/panel2-sheet0.png",
		"images/rogershead-sheet0.png",
		"images/preloaderfont.png",
		"images/preloadersf.png",
		"images/scoretf2.png",
		"images/preloaderfont2.png",
		"images/progresstf.png",
		"images/rotatescreenbg.png",
		"images/pleaserotatescreensprite-sheet0.png",
		"images/aliengranade_-sheet0.png",
		"images/animacjalecacychlusek_-sheet0.png",
		"images/animacjalecacychlusek_-sheet1.png",
		"images/pojedynczaluska-sheet0.png",
		"images/dymzapociskiemzbazooki_-sheet0.png",
		"images/nextupgrade-sheet0.png",
		"images/upgradeclaiminfo-sheet0.png",
		"images/upgradeclaiminfo-sheet1.png",
		"images/upgradeclaiminfo-sheet2.png",
		"images/progressbar-sheet0.png",
		"images/yourdailyquest-sheet0.png",
		"images/playergun-sheet0.png",
		"images/playergun-sheet1.png",
		"images/playergun-sheet2.png",
		"images/upgradechesttank-sheet0.png",
		"images/upgradechesttank-sheet1.png",
		"images/newupgradechest_shadow-sheet0.png",
		"images/upgradeinfo2-sheet0.png",
		"images/upgradeinfo2-sheet1.png",
		"images/missiontitleicon-sheet0.png",
		"images/missiontitleicon-sheet1.png",
		"images/missionlabel.png",
		"images/claimupgrade-sheet0.png",
		"images/storytext.png",
		"images/missiontitleparta-sheet0.png",
		"images/missiontitleparta-sheet1.png",
		"images/swipeupforgranade2-sheet0.png",
		"images/swipeupforgranade2-sheet1.png",
		"media/alien die_03.m4a",
		"media/alien die_03.ogg",
		"media/alien hit by bullet.m4a",
		"media/alien hit by bullet.ogg",
		"media/cartoon tap_02.m4a",
		"media/cartoon tap_02.ogg",
		"media/comando dezintergration_03.m4a",
		"media/comando dezintergration_03.ogg",
		"media/explosion_02.m4a",
		"media/explosion_02.ogg",
		"media/lazer shot_03.m4a",
		"media/lazer shot_03.ogg",
		"media/pick up grenade_01.m4a",
		"media/pick up grenade_01.ogg",
		"media/pickup medal_01.m4a",
		"media/pickup medal_01.ogg",
		"media/blackmoonding.m4a",
		"media/blackmoonding.ogg",
		"media/commadodostal5.m4a",
		"media/commadodostal5.ogg",
		"media/machinegun_normalciszej.m4a",
		"media/machinegun_normalciszej.ogg",
		"media/machinegun_normal_superbassciszej.m4a",
		"media/machinegun_normal_superbassciszej.ogg",
		"media/cyborg run.m4a",
		"media/cyborg run.ogg",
		"media/bazookalaunch.m4a",
		"media/bazookalaunch.ogg",
		"media/laser shot_1.m4a",
		"media/laser shot_1.ogg",
		"media/upgrade_shotgun.m4a",
		"media/upgrade_shotgun.ogg",
		"media/cardswipe_04.m4a",
		"media/cardswipe_04.ogg",
		"media/power-up 1.m4a",
		"media/power-up 1.ogg",
		"media/laser hitting the target_4.m4a",
		"media/laser hitting the target_4.ogg",
		"media/power-up_przerobiony_na_koniec.m4a",
		"media/power-up_przerobiony_na_koniec.ogg",
		"media/power-up 103.m4a",
		"media/power-up 103.ogg",
		"media/laser_01.m4a",
		"media/laser_01.ogg",
		"media/laser_03.m4a",
		"media/laser_03.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}